### ISSUE TITLE
Fetching data from samsung health

### ISSUE THREAD

**Issue by juroc95** [psu-software-engineering-capstone/walktober#124]
- Research the Samsung Health API and determine the specific endpoint(s) needed to retrieve step count data.
- Use the Ionic native Health plugin to connect to Samsung Health
- Use the appropriate function to fetch step count data, it depends on the version of Samsung Health API
- Handle any errors that may occur during the data retrieval process and implement proper error handling.
- Test the functionality on a Samsung device that has Samsung Health installed and configured.
- Finally, integrate the data retrieval functionality into our Ionic React app and test it thoroughly.

**Comment by aphamdd** [comment]
https://forum.developer.samsung.com/t/samsung-health-not-writing-steps-to-health-connect/23284/5
Looks like theres a possibility of Samsung health writing steps to health connect again
Will look into this
