### ISSUE TITLE
Profile page (change password & change profile picture)

### ISSUE THREAD

**Issue by juroc95** [psu-software-engineering-capstone/walktober#164]
## change password & change profile pic

- Use auth variable and Firebase SDK
- https://firebase.google.com/docs/auth/web/manage-users

**Comment by marobertson11** [comment]
google authentication: pull profile picture from google
personal authentication: upload own picture after profile has been made

**Comment by marobertson11** [comment]
google authenticating already loads the profile picture, forgot to add this detail earlier
