### ISSUE TITLE
New registration process

### ISSUE THREAD

**Issue by juroc95** [psu-software-engineering-capstone/walktober#182]
## should have
- completion of sign-up should redirect to the registration question page
- completion of the registration questions should redirect to the home page (skipping the log-in page)
- answers to the registration questions should be stored in a database (by users)
## could have
- add email verification in the sign-up process
- https://firebase.google.com/docs/auth/web/email-link-auth?hl=ko&authuser=0

**Comment by melis29** [comment]
https://firebase.blog/posts/2017/02/email-verification-in-firebase-auth - this is for my future reference

**Comment by melis29** [comment]
verification email goes to spam - solution is on this https://stackoverflow.com/questions/46283859/firebase-email-verification-goes-to-spam-folder

**need to verify our domain once we have it?

**Comment by juroc95** [comment]
> verification email goes to spam - solution is on this https://stackoverflow.com/questions/46283859/firebase-email-verification-goes-to-spam-folder
> 
> **need to verify our domain once we have it?

that's weird. reset password also uses a similar template, but it does not go to spam.

**Comment by melis29** [comment]
Maybe its a yahoo thing? I'll try doing the forgot password with the yahoo email

**Comment by melis29** [comment]
I already added the domain to that yahoo email nevermind

**Comment by melis29** [comment]
checked using gmail - gmail was fine and didn't send to spam. Maybe its just yahoo
