### ISSUE TITLE
Health app auto sync

### ISSUE THREAD

**Issue by juroc95** [psu-software-engineering-capstone/walktober#195]
## should have
- users should be able to choose between apple health or google fit
- once the user chooses their health app, the app then should request permission from apple health or google fit
- once the permission is done, the step count should be updated, and inform the user that the health app is connected.
- then the user info should be updated (device: apple health / google fit).
- once the user completes the health app setup, the step count should be updated whenever the user opens the app.

## could have
- option to disconnect from apple health or google fit

**Comment by aphamdd** [comment]
note to self
- TODO: use the functions in HealthApp.tsx instead of copy pasting them in HomePage.tsx and manualLoggingSteps.tsx

**Comment by aphamdd** [comment]
Self-note
- reduce clone code
